services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      TZ: Asia/Colombo
    volumes:
      - ./mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - la-fresca-network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    env_file: .env
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_SERVER: $ME_CONFIG_MONGODB_SERVER
      ME_CONFIG_BASICAUTH_USERNAME: $ME_CONFIG_BASICAUTH_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $ME_CONFIG_BASICAUTH_PASSWORD
    networks:
      - la-fresca-network
  simple-upload:
    build: ./simple-upload
    container_name: simple-upload
    networks:
      - la-fresca-network
    volumes:
      - ./simple-upload/uploads:/usr/src/app/uploads
  la-fresca-backend:
    build: ./la-fresca-backend
    container_name: la-fresca-backend
    environment:
      - DATABASE_URL=$LAFRESCA_DB
    networks:
      - la-fresca-network
  la-fresca-frontend:
    build: ./la-fresca-frontend
    depends_on:
      - la-fresca-backend
    container_name: la-fresca-frontend
    networks:
      - la-fresca-network
  la-fresca-sysadmin-service:
    build: ./la-fresca-sysadmin-service
    container_name: la-fresca-sysadmin-service
    networks:
      - la-fresca-network
    environment:
      - MONGO_URI=$LAFRESCA_DB
      - DROPBOX_TOKEN=$DROPBOX_TOKEN
      - JWT_SECRET=$JWT_SECRET

networks:
  la-fresca-network:
    driver: bridge
